version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - /home/ec2-user/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - koner
    
  koner:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
     - "3000:3000"
    volumes:
     - /usr/src/app/node_modules # 로컬에 node_modules 없으니 매핑하지 말라
     - /jenkins/workspace/koner-front-pipeline/:/usr/src/app # 매핑
    stdin_open: true # docker run의 -i 옵션. react 한정으로 필요함.
    restart: on-failure